name: Trigger auto deployment for aca-careersync

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ develop ]
    paths:
    - '**'
    - '.github/workflows/aca-careersync-AutoDeployTrigger-be4d5130-07b3-4053-8dd2-f959f277abe2.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ACACAREERSYNC_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ACACAREERSYNC_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ACACAREERSYNC_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: docker.io
          registryUsername: ${{ secrets.ACACAREERSYNC_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ACACAREERSYNC_REGISTRY_PASSWORD }}
          containerAppName: aca-careersync
          resourceGroup: careersync
          imageToBuild: gdsc-solution-challenge-team4-pointer/aca-careersync:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


